name = "whoistrs-worker"
main = "index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/10 * * * *"]

# Secrets — set via `wrangler secret put BACKEND_URL` (never commit values here)

[[kv_namespaces]]
binding = "WHOISTRS_KV"
id = "bdeb59ea9afe48c69dfaf1e642f56d28"
